const fonts = [
    { label: '1Row', value: '1Row' },
    { label: '3-D', value: '3-D' },
    { label: '3D Diagonal', value: '3D Diagonal' },
    { label: '3D-ASCII', value: '3D-ASCII' },
    { label: '3x5', value: '3x5' },
    { label: '4Max', value: '4Max' },
    { label: '5 Line Oblique', value: '5 Line Oblique' },
    { label: 'AMC 3 Line', value: 'AMC 3 Line' },
    { label: 'AMC 3 Liv1', value: 'AMC 3 Liv1' },
    { label: 'AMC AAA01', value: 'AMC AAA01' },
    { label: 'AMC Neko', value: 'AMC Neko' },
    { label: 'AMC Razor', value: 'AMC Razor' },
    { label: 'AMC Razor2', value: 'AMC Razor2' },
    { label: 'AMC Slash', value: 'AMC Slash' },
    { label: 'AMC Slider', value: 'AMC Slider' },
    { label: 'AMC Thin', value: 'AMC Thin' },
    { label: 'AMC Tubes', value: 'AMC Tubes' },
    { label: 'AMC Untitled', value: 'AMC Untitled' },
    { label: 'ANSI Regular', value: 'ANSI Regular' },
    { label: 'ANSI Shadow', value: 'ANSI Shadow' },
    { label: 'ASCII New Roman', value: 'ASCII New Roman' },
    { label: 'Acrobatic', value: 'Acrobatic' },
    { label: 'Alligator', value: 'Alligator' },
    { label: 'Alligator2', value: 'Alligator2' },
    { label: 'Alpha', value: 'Alpha' },
    { label: 'Alphabet', value: 'Alphabet' },
    { label: 'Arrows', value: 'Arrows' },
    { label: 'Avatar', value: 'Avatar' },
    { label: 'B1FF', value: 'B1FF' },
    { label: 'Banner', value: 'Banner' },
    { label: 'Banner3-D', value: 'Banner3-D' },
    { label: 'Banner3', value: 'Banner3' },
    { label: 'Banner4', value: 'Banner4' },
    { label: 'Barbwire', value: 'Barbwire' },
    { label: 'Basic', value: 'Basic' },
    { label: 'Bear', value: 'Bear' },
    { label: 'Bell', value: 'Bell' },
    { label: 'Benjamin', value: 'Benjamin' },
    { label: 'Big Chief', value: 'Big Chief' },
    { label: 'Big Money-ne', value: 'Big Money-ne' },
    { label: 'Big Money-nw', value: 'Big Money-nw' },
    { label: 'Big Money-se', value: 'Big Money-se' },
    { label: 'Big Money-sw', value: 'Big Money-sw' },
    { label: 'Big', value: 'Big' },
    { label: 'Bigfig', value: 'Bigfig' },
    { label: 'Binary', value: 'Binary' },
    { label: 'Block', value: 'Block' },
    { label: 'Blocks', value: 'Blocks' },
    { label: 'Bloody', value: 'Bloody' },
    { label: 'Bolger', value: 'Bolger' },
    { label: 'Braced', value: 'Braced' },
    { label: 'Bright', value: 'Bright' },
    { label: 'Broadway KB', value: 'Broadway KB' },
    { label: 'Broadway', value: 'Broadway' },
    { label: 'Bubble', value: 'Bubble' },
    { label: 'Bulbhead', value: 'Bulbhead' },
    { label: 'Caligraphy', value: 'Caligraphy' },
    { label: 'Caligraphy2', value: 'Caligraphy2' },
    { label: 'Calvin S', value: 'Calvin S' },
    { label: 'Cards', value: 'Cards' },
    { label: 'Catwalk', value: 'Catwalk' },
    { label: 'Chiseled', value: 'Chiseled' },
    { label: 'Chunky', value: 'Chunky' },
    { label: 'Coinstak', value: 'Coinstak' },
    { label: 'Cola', value: 'Cola' },
    { label: 'Colossal', value: 'Colossal' },
    { label: 'Computer', value: 'Computer' },
    { label: 'Contessa', value: 'Contessa' },
    { label: 'Contrast', value: 'Contrast' },
    { label: 'Cosmike', value: 'Cosmike' },
    { label: 'Crawford', value: 'Crawford' },
    { label: 'Crawford2', value: 'Crawford2' },
    { label: 'Crazy', value: 'Crazy' },
    { label: 'Cricket', value: 'Cricket' },
    { label: 'Cursive', value: 'Cursive' },
    { label: 'Cyberlarge', value: 'Cyberlarge' },
    { label: 'Cybermedium', value: 'Cybermedium' },
    { label: 'Cybersmall', value: 'Cybersmall' },
    { label: 'Cygnet', value: 'Cygnet' },
    { label: 'DANC4', value: 'DANC4' },
    { label: 'DOS Rebel', value: 'DOS Rebel' },
    { label: 'DWhistled', value: 'DWhistled' },
    { label: 'Dancing Font', value: 'Dancing Font' },
    { label: 'Decimal', value: 'Decimal' },
    { label: 'Def Leppard', value: 'Def Leppard' },
    { label: 'Delta Corps Priest 1', value: 'Delta Corps Priest 1' },
    { label: 'Diamond', value: 'Diamond' },
    { label: 'Diet Cola', value: 'Diet Cola' },
    { label: 'Digital', value: 'Digital' },
    { label: 'Doh', value: 'Doh' },
    { label: 'Doom', value: 'Doom' },
    { label: 'Dot Matrix', value: 'Dot Matrix' },
    { label: 'Double Shorts', value: 'Double Shorts' },
    { label: 'Double', value: 'Double' },
    { label: 'Dr Pepper', value: 'Dr Pepper' },
    { label: 'Efti Chess', value: 'Efti Chess' },
    { label: 'Efti Font', value: 'Efti Font' },
    { label: 'Efti Italic', value: 'Efti Italic' },
    { label: 'Efti Piti', value: 'Efti Piti' },
    { label: 'Efti Robot', value: 'Efti Robot' },
    { label: 'Efti Wall', value: 'Efti Wall' },
    { label: 'Efti Water', value: 'Efti Water' },
    { label: 'Electronic', value: 'Electronic' },
    { label: 'Elite', value: 'Elite' },
    { label: 'Epic', value: 'Epic' },
    { label: 'Fender', value: 'Fender' },
    { label: 'Filter', value: 'Filter' },
    { label: 'Fire Font-k', value: 'Fire Font-k' },
    { label: 'Fire Font-s', value: 'Fire Font-s' },
    { label: 'Flipped', value: 'Flipped' },
    { label: 'Flower Power', value: 'Flower Power' },
    { label: 'Four Tops', value: 'Four Tops' },
    { label: 'Fraktur', value: 'Fraktur' },
    { label: 'Fun Face', value: 'Fun Face' },
    { label: 'Fun Faces', value: 'Fun Faces' },
    { label: 'Fuzzy', value: 'Fuzzy' },
    { label: 'Georgi16', value: 'Georgi16' },
    { label: 'Georgia11', value: 'Georgia11' },
    { label: 'Ghost', value: 'Ghost' },
    { label: 'Ghoulish', value: 'Ghoulish' },
    { label: 'Glenyn', value: 'Glenyn' },
    { label: 'Goofy', value: 'Goofy' },
    { label: 'Gothic', value: 'Gothic' },
    { label: 'Graceful', value: 'Graceful' },
    { label: 'Gradient', value: 'Gradient' },
    { label: 'Graffiti', value: 'Graffiti' },
    { label: 'Greek', value: 'Greek' },
    { label: 'Heart Left', value: 'Heart Left' },
    { label: 'Heart Right', value: 'Heart Right' },
    { label: 'Henry 3D', value: 'Henry 3D' },
    { label: 'Hex', value: 'Hex' },
    { label: 'Hieroglyphs', value: 'Hieroglyphs' },
    { label: 'Hollywood', value: 'Hollywood' },
    { label: 'Horizontal Left', value: 'Horizontal Left' },
    { label: 'Horizontal Right', value: 'Horizontal Right' },
    { label: 'ICL-1900', value: 'ICL-1900' },
    { label: 'Impossible', value: 'Impossible' },
    { label: 'Invita', value: 'Invita' },
    { label: 'Isometric1', value: 'Isometric1' },
    { label: 'Isometric2', value: 'Isometric2' },
    { label: 'Isometric3', value: 'Isometric3' },
    { label: 'Isometric4', value: 'Isometric4' },
    { label: 'Italic', value: 'Italic' },
    { label: 'Ivrit', value: 'Ivrit' },
    { label: 'JS Block Letters', value: 'JS Block Letters' },
    { label: 'JS Bracket Letters', value: 'JS Bracket Letters' },
    { label: 'JS Capital Curves', value: 'JS Capital Curves' },
    { label: 'JS Cursive', value: 'JS Cursive' },
    { label: 'JS Stick Letters', value: 'JS Stick Letters' },
    { label: 'Jacky', value: 'Jacky' },
    { label: 'Jazmine', value: 'Jazmine' },
    { label: 'Jerusalem', value: 'Jerusalem' },
    { label: 'Katakana', value: 'Katakana' },
    { label: 'Kban', value: 'Kban' },
    { label: 'Keyboard', value: 'Keyboard' },
    { label: 'Knob', value: 'Knob' },
    { label: 'Konto Slant', value: 'Konto Slant' },
    { label: 'Konto', value: 'Konto' },
    { label: 'LCD', value: 'LCD' },
    { label: 'Larry 3D 2', value: 'Larry 3D 2' },
    { label: 'Larry 3D', value: 'Larry 3D' },
    { label: 'Lean', value: 'Lean' },
    { label: 'Letters', value: 'Letters' },
    { label: 'Lil Devil', value: 'Lil Devil' },
    { label: 'Line Blocks', value: 'Line Blocks' },
    { label: 'Linux', value: 'Linux' },
    { label: 'Lockergnome', value: 'Lockergnome' },
    { label: 'Madrid', value: 'Madrid' },
    { label: 'Marquee', value: 'Marquee' },
    { label: 'Maxfour', value: 'Maxfour' },
    { label: 'Merlin1', value: 'Merlin1' },
    { label: 'Merlin2', value: 'Merlin2' },
    { label: 'Mike', value: 'Mike' },
    { label: 'Mini', value: 'Mini' },
    { label: 'Mirror', value: 'Mirror' },
    { label: 'Mnemonic', value: 'Mnemonic' },
    { label: 'Modular', value: 'Modular' },
    { label: 'Morse', value: 'Morse' },
    { label: 'Morse2', value: 'Morse2' },
    { label: 'Moscow', value: 'Moscow' },
    { label: 'Mshebrew210', value: 'Mshebrew210' },
    { label: 'Muzzle', value: 'Muzzle' },
    { label: 'NScript', value: 'NScript' },
    { label: 'NT Greek', value: 'NT Greek' },
    { label: 'NV Script', value: 'NV Script' },
    { label: 'Nancyj-Fancy', value: 'Nancyj-Fancy' },
    { label: 'Nancyj-Improved', value: 'Nancyj-Improved' },
    { label: 'Nancyj-Underlined', value: 'Nancyj-Underlined' },
    { label: 'Nancyj', value: 'Nancyj' },
    { label: 'Nipples', value: 'Nipples' },
    { label: 'O8', value: 'O8' },
    { label: 'OS2', value: 'OS2' },
    { label: 'Octal', value: 'Octal' },
    { label: 'Ogre', value: 'Ogre' },
    { label: 'Old Banner', value: 'Old Banner' },
    { label: 'Pagga', value: 'Pagga' },
    { label: "Patorjk's Cheese", value: "Patorjk's Cheese" },
    { label: 'Patorjk-HeX', value: 'Patorjk-HeX' },
    { label: 'Pawp', value: 'Pawp' },
    { label: 'Peaks Slant', value: 'Peaks Slant' },
    { label: 'Peaks', value: 'Peaks' },
    { label: 'Pebbles', value: 'Pebbles' },
    { label: 'Pepper', value: 'Pepper' },
    { label: 'Poison', value: 'Poison' },
    { label: 'Puffy', value: 'Puffy' },
    { label: 'Puzzle', value: 'Puzzle' },
    { label: 'Pyramid', value: 'Pyramid' },
    { label: 'Rammstein', value: 'Rammstein' },
    { label: 'Rectangles', value: 'Rectangles' },
    { label: 'Red Phoenix', value: 'Red Phoenix' },
    { label: 'Relief', value: 'Relief' },
    { label: 'Relief2', value: 'Relief2' },
    { label: 'Reverse', value: 'Reverse' },
    { label: 'Roman', value: 'Roman' },
    { label: 'Rot13', value: 'Rot13' },
    { label: 'Rotated', value: 'Rotated' },
    { label: 'Rounded', value: 'Rounded' },
    { label: 'Rowan Cap', value: 'Rowan Cap' },
    { label: 'Rozzo', value: 'Rozzo' },
    { label: 'Runic', value: 'Runic' },
    { label: 'Runyc', value: 'Runyc' },
    { label: 'S Blood', value: 'S Blood' },
    { label: 'SL Script', value: 'SL Script' },
    { label: 'Santa Clara', value: 'Santa Clara' },
    { label: 'Script', value: 'Script' },
    { label: 'Serifcap', value: 'Serifcap' },
    { label: 'Shadow', value: 'Shadow' },
    { label: 'Shimrod', value: 'Shimrod' },
    { label: 'Short', value: 'Short' },
    { label: 'Slant Relief', value: 'Slant Relief' },
    { label: 'Slant', value: 'Slant' },
    { label: 'Slide', value: 'Slide' },
    { label: 'Small Caps', value: 'Small Caps' },
    { label: 'Small Isometric1', value: 'Small Isometric1' },
    { label: 'Small Keyboard', value: 'Small Keyboard' },
    { label: 'Small Poison', value: 'Small Poison' },
    { label: 'Small Script', value: 'Small Script' },
    { label: 'Small Shadow', value: 'Small Shadow' },
    { label: 'Small Slant', value: 'Small Slant' },
    { label: 'Small Tengwar', value: 'Small Tengwar' },
    { label: 'Small', value: 'Small' },
    { label: 'Soft', value: 'Soft' },
    { label: 'Speed', value: 'Speed' },
    { label: 'Spliff', value: 'Spliff' },
    { label: 'Stacey', value: 'Stacey' },
    { label: 'Stampate', value: 'Stampate' },
    { label: 'Stampatello', value: 'Stampatello' },
    { label: 'Standard', value: 'Standard' },
    { label: 'Star Strips', value: 'Star Strips' },
    { label: 'Star Wars', value: 'Star Wars' },
    { label: 'Stellar', value: 'Stellar' },
    { label: 'Stforek', value: 'Stforek' },
    { label: 'Stick Letters', value: 'Stick Letters' },
    { label: 'Stop', value: 'Stop' },
    { label: 'Straight', value: 'Straight' },
    { label: 'Stronger Than All', value: 'Stronger Than All' },
    { label: 'Sub-Zero', value: 'Sub-Zero' },
    { label: 'Swamp Land', value: 'Swamp Land' },
    { label: 'Swan', value: 'Swan' },
    { label: 'Sweet', value: 'Sweet' },
    { label: 'THIS', value: 'THIS' },
    { label: 'Tanja', value: 'Tanja' },
    { label: 'Tengwar', value: 'Tengwar' },
    { label: 'Term', value: 'Term' },
    { label: 'Test1', value: 'Test1' },
    { label: 'The Edge', value: 'The Edge' },
    { label: 'Thick', value: 'Thick' },
    { label: 'Thin', value: 'Thin' },
    { label: 'Thorned', value: 'Thorned' },
    { label: 'Three Point', value: 'Three Point' },
    { label: 'Ticks Slant', value: 'Ticks Slant' },
    { label: 'Ticks', value: 'Ticks' },
    { label: 'Tiles', value: 'Tiles' },
    { label: 'Tinker-Toy', value: 'Tinker-Toy' },
    { label: 'Tombstone', value: 'Tombstone' },
    { label: 'Train', value: 'Train' },
    { label: 'Trek', value: 'Trek' },
    { label: 'Tsalagi', value: 'Tsalagi' },
    { label: 'Tubular', value: 'Tubular' },
    { label: 'Twisted', value: 'Twisted' },
    { label: 'Two Point', value: 'Two Point' },
    { label: 'USA Flag', value: 'USA Flag' },
    { label: 'Univers', value: 'Univers' },
    { label: 'Varsity', value: 'Varsity' },
    { label: 'Wavy', value: 'Wavy' },
    { label: 'Weird', value: 'Weird' },
    { label: 'Wet Letter', value: 'Wet Letter' },
    { label: 'Whimsy', value: 'Whimsy' },
    { label: 'Wow', value: 'Wow' },
  ]
  export { fonts }
  